export const FETCH_BREEDS = 'FETCH_BREEDS';
export const SEARCH_BREED_CHANGE = 'SEARCH_BREED_CHANGE';
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const SET_ACTIVE_IMAGE_INDEX = 'SET_ACTIVE_IMAGE_INDEX';
